### ISSUE TITLE
need to get Y variable in auto paddle.

### ISSUE THREAD

**Issue by joeymizrahi** [CS-Programmers-Projects/Pong#20]
https://github.com/CS-Programmers-Projects/Pong/blob/5d5533ce1942b3b9607e651a8977929b2cb77b57/AutoPaddle.py#L7

**Comment by msj1995** [comment]
what is the Y variable. i thought it was the h as in for height?

**Comment by joeymizrahi** [comment]
the w, h are width and height for the paddle. 
The x,y are point on where to insert the paddle on the screen

**Comment by joeymizrahi** [comment]
no longer needed
